// Generates src/generated/schema.ts from the saved live OpenAPI snapshot.
// Patches below correct the spec where the live API provably differs
// (see docs/api/probes-2026-09-09.md). Re-run: pnpm generate:types
import { readFileSync, writeFileSync } from "node:fs";
import openapiTS, { astToString } from "openapi-typescript";

const SPEC = new URL("../../../docs/api/hevy-openapi.2026-09-09.json", import.meta.url);
const OUT = new URL("../src/generated/schema.ts", import.meta.url);
const SET_TYPES = ["normal", "warmup", "dropset", "failure"];

const spec = JSON.parse(readFileSync(SPEC, "utf8"));
const schemas = spec.components.schemas;

// Spec uses the invalid `type: "enum"`; openapi-typescript needs `type: "string"`.
for (const s of Object.values(schemas)) if (s.type === "enum") s.type = "string";

// `required: true` on a property is invalid OpenAPI; the body requires `exercise`.
const custom = schemas.CreateCustomExerciseRequestBody;
delete custom.properties.exercise.required;
custom.required = ["exercise"];

// Set.type is documented as one of four values but typed as free string.
schemas.Set.properties.type.enum = SET_TYPES;
for (const name of ["Workout", "Routine"]) {
  schemas[name].properties.exercises.items.properties.sets.items.properties.type.enum = SET_TYPES;
}

// Probes §5: rest_seconds is a number on live responses, spec says string.
schemas.Routine.properties.exercises.items.properties.rest_seconds.type = "number";

// Probes §6: body measurement responses carry id and created_at.
schemas.BodyMeasurement.properties.id = { type: "number" };
schemas.BodyMeasurement.properties.created_at = { type: "string" };

// Events are a discriminated union on `type`; the spec only gives examples.
schemas.UpdatedWorkout.properties.type.enum = ["updated"];
schemas.DeletedWorkout.properties.type.enum = ["deleted"];

// Probes §6: routine_id is null for workouts not started from a routine.
schemas.Workout.properties.routine_id.nullable = true;

// Response schemas declare no `required`, so every field would be optional.
// Live responses always include every key (probes §6), except rep_range on routine sets
// and the optional fields of BodyMeasurement, which are omitted when unset.
const ALWAYS_PRESENT = [
  "Workout",
  "Routine",
  "RoutineFolder",
  "ExerciseTemplate",
  "ExerciseHistoryEntry",
  "UserInfo",
  "UserInfoResponse",
  "UpdatedWorkout",
  "DeletedWorkout",
  "PaginatedWorkoutEvents",
];
const OMITTED_WHEN_UNSET = new Set(["rep_range"]);
function requireAll(schema) {
  if (schema.type !== "object" || !schema.properties) return;
  schema.required = Object.keys(schema.properties).filter((k) => !OMITTED_WHEN_UNSET.has(k));
  for (const prop of Object.values(schema.properties)) requireAll(prop.items ?? prop);
}
for (const name of ALWAYS_PRESENT) requireAll(schemas[name]);
schemas.BodyMeasurement.required = ["id", "date", "created_at"];

const ast = await openapiTS(spec, { alphabetize: false });
const header = `// AUTO-GENERATED by scripts/generate-types.mjs from ${SPEC.pathname.split("/").slice(-1)[0]}. Do not edit.\n`;
writeFileSync(OUT, header + astToString(ast));
console.log("wrote", OUT.pathname);
